name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3.5.2
    - name: MSBuild Setup
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Nuget Setup
      uses: nuget/setup-nuget@v1.2.0
      with:
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    - name: Restore
      run: nuget restore src/Xamarin.iOS.ResourceDesigner.NuGet.sln
    - name: Build
      run: msbuild src/Xamarin.iOS.ResourceDesigner/Xamarin.iOS.ResourceDesigner.csproj /property:Configuration=Release /warnaserror
    - name: Find package path
      id: find_package_path
      run: |
        # Find the nupkg file with the required structure
        packagePath=$(find src/Xamarin.iOS.ResourceDesigner/bin/Release -type f -name "Xamarin.iOS.ResourceDesigner.*.nupkg" | head -n 1)
        echo "Found package on the path:"
        echo "$packagePath"
        echo "::set-output name=package_path::$packagePath"
    - name: Publish
      uses: dansiegel/publish-nuget@v1.2
      with:
        filename: ${{ steps.find_package_path.outputs.package_path }}
        apiKey: ${{ secrets.NUGET_API_KEY }}
    - name: SetVersionTag
      run: |
        packagePath=${{ steps.find_package_path.outputs.package_path }}
        packageVersion=${packagePath##Xamarin.iOS.ResourceDesigner.}
        packageVersion=${packageVersion%.nupkg}
        packageVersionTag="v$packageVersion"
        echo "Pushing tag '$packageVersionTag'"
        git tag "$packageVersionTag"
        git push --tags
