name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3.5.2
    - name: MSBuild Setup
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Nuget Setup
      uses: nuget/setup-nuget@v1.2.0
      with:
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    - name: Restore
      run: nuget restore src/Xamarin.iOS.ResourceDesigner.NuGet.sln
    - name: Build
      run: msbuild src/Xamarin.iOS.ResourceDesigner/Xamarin.iOS.ResourceDesigner.csproj /property:Configuration=Release /warnaserror
    - name: Find package path
      id: find_package_path
      run: |
        # Find the nupkg file with the required structure
        $packagePath = Get-ChildItem -Path "src/Xamarin.iOS.ResourceDesigner/bin/Release" -Recurse -Filter "Xamarin.iOS.ResourceDesigner.*.nupkg" | Select-Object -First 1
        Write-Host "Found package path:"
        Write-Host "$packagePath"
        Write-Output "::set-output name=package_path::$packagePath"
    - name: Publish
      uses: dansiegel/publish-nuget@v1.2
      with:
        filename: ${{ steps.find_package_path.outputs.package_path }}
        apiKey: ${{ secrets.NUGET_API_KEY }}
    - name: SetVersionTag
      run: |
        $packagePath = ${{ steps.extract_version.outputs.package_path }}
        $prefix = "Xamarin.iOS.ResourceDesigner."
        $suffix = ".nupkg"
        $startIndex = $packagePath.IndexOf($prefix) + $prefix.Length
        $endIndex = $packagePath.IndexOf($suffix, $startIndex)
        $packageVersion = $packagePath.Substring($startIndex, $endIndex - $startIndex)
        packageVersionTag="v$packageVersion"
        Write-Host "Pushing tag '$packageVersionTag'"
        git tag "$packageVersionTag"
        git push --tags
